language: r
env:
    global:
        - TRAVIS_R_VERSION=4.0.0
r:
cache: packages
sudo: false
warnings_are_errors: false
bioc_required: true
before_install:
  - sudo apt-get -y install libgsl0-dev
  - Rscript -e 'update.packages(ask = FALSE)'
r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes --no-build-vignettes --as-cran"
addons:
  apt:
    packages:
    - libmpfr-dev

r_github_packages:
  - r-lib/covr
  - jimhester/lintr
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'library(lintr); lint_package(linters = with_defaults(object_length_linter(length = 80L), object_name_linter = NULL, commented_code_linter = NULL, object_usage_linter = NULL)'
