language: r
env:
    global:
        - TRAVIS_R_VERSION=4.0.0
cache: packages
sudo: false
warnings_are_errors: true
bioc_required: true
r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes --no-build-vignettes --as-cran"
r_github_packages:
  - r-lib/covr
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'covr::coveralls()'
