---
title: "BAGEL_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BAGEL_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library("BAGEL")
```

```{r}
#Find Signatures examples
#' bay <- readRDS(system.file("testdata", "bagel_snv96.rds", package = "BAGEL"))
#' res <- discover_signatures(bay, "SNV96", num_signatures = 4)

#Load MAF File
lusc_maf <- system.file("testdata", "public_TCGA.LUSC.maf", package = "BAGEL") 
lusc <- BAGEL::maf_file_to_dt(maf_file = lusc_maf)

#Load individual VCF Files
luad1_vcf <- system.file("testdata", "public_LUAD_TCGA-97-7938.vcf", 
                         package = "BAGEL")
luad1 <- BAGEL::vcf_file_to_dt(vcf_file = luad1_vcf)
luad2_vcf <- system.file("testdata", "public_LUAD_TCGA-MP-A4TJ.vcf", 
                         package = "BAGEL")
luad2 <- BAGEL::vcf_file_to_dt(vcf_file = luad2_vcf)

#Load Multiple VCF Files At Once using list files with regular expressions
melanoma_vcf <- list.files(system.file("testdata", package = "BAGEL"), 
                           pattern = glob2rx("*SKCM*vcf"), full.names = TRUE)
melanoma <- BAGEL::vcf_files_to_dt(vcf_files = melanoma_vcf)

#Combine all data.frames
dat <- rbind(lusc, melanoma, luad1, luad2)

#Choose genome build
#Automatically detect genome build
#g=BAGEL::select_genome("38")

#Create Object and add samples
bagel = new("bagel")
variants = dat
BAGEL::set_variants(bagel, variants)

#Or alternatively create an object with sample names included
bagel = new("bagel", variants = dat)

#Display what samples were added
BAGEL::get_sample_names(bagel)

# Create 96 Motif samples
g = select_genome("38")
#Generates the "SNV96" table
build_standard_table(bagel, g, "SNV96")

# Generate signatures/weights
# We can use the bagel object we generated tables for using the SNV96 table
result = discover_signatures(input = bagel, table_name = "SNV96", 
                              num_signatures = 4, method = "nmf")

##We can name signatures based on prior knowledge
name_signatures(result, c("unknown", "smoking", "apobec", "uv"))

##Plot results
plot_signatures(result)
plot_exposures(result, proportional = TRUE)
plot_exposures(result, proportional = FALSE)
#
##Compare to COSMIC signatures by leaving the second result as default
compare_cosmic_v2(result, threshold = 0.8)

#List which signatures correspond to subtypes including "lung"
cosmic_v2_subtype_map("lung")

#Calculate posterior based on COSMIC signatures 4, 11, 12, 15
cosmic_post = predict_exposure(bagel = bagel, "SNV96", signature_res = 
                                 cosmic_v2_sigs, signatures_to_use = 
                                 c(12, 4, 11, 15))
#cosmic_post = predict_exposure(bagel = bagel)
#to_use = as.numeric(substr(names(which(rowSums(cosmic_post@exposures) > 10^-10)), 11, 12))
#to_use = as.numeric(substr(names(which(apply(cosmic_post@exposures, 1, max) > 10^-10)), 11, 12))
#cosmic_post = predict_exposure(bagel = bagel, signatures_to_use = to_use)

#Calculate posterior based on all calculated signatures
our_sigs_post = predict_exposure(bagel = bagel, "SNV96", signature_res = 
                                   result)

#Plot results from posterior calculation
plot_signatures(cosmic_post)
plot_exposures(cosmic_post, proportional = TRUE)

BAGEL::plot_signatures(our_sigs_post)
BAGEL::plot_exposures(our_sigs_post, proportional = TRUE)

#Compare posterior results to each other
BAGEL::compare_results(cosmic_post, our_sigs_post, threshold = 0.70)

BAGEL::plot_sample_counts(bagel, "SNV96", get_sample_names(bagel)[1])
############################################## Error up here ^^^^^
sample_annotations <- read.table(system.file("testdata", "sample_annotations.txt", package = "BAGEL"), sep = "\t", header=TRUE)
init_sample_annotations(bagel)
add_sample_annotations(bagel, sample_annotations, sample_column = "Sample_Names", columns_to_add = "Tumor_Subtypes")
#
##Add tumor type annotations to our samples
#res <- discover_signatures(bagel, table_name = "SNV96", num_signatures = 3)
res <- readRDS(system.file("testdata", "test_res.rds", package = "BAGEL"))
plot_exposures_by_annotation(res, annotation = "Tumor_Subtypes")
plot_exposures_by_annotation(res, annotation = "Tumor_Subtypes", proportional = FALSE)
plot_exposures_by_annotation(res, annotation = "Tumor_Subtypes", by_group = FALSE)
plot_exposures_by_annotation(res, annotation = "Tumor_Subtypes", by_group = FALSE, proportional = FALSE)

#Discover stranded SNV signatures
#brca = maf_file_to_dt("/Users/atgc/Downloads/gdc_download_20200609_120830.134740/995c0111-d90#b-4140-bee7-3845436c3b42/TCGA.BRCA.mutect.995c0111-d90b-4140-bee7-3845436c3b42.DR-10.0.somati#c.maf")
#bagel = new("bagel", variants = brca)
#
#BAGEL::build_standard_table(bagel, g, "SNV96")
#BAGEL::annotate_variant_type(bagel)
#BAGEL::annotate_transcript_strand(bagel, 38)
#BAGEL::annotate_replication_strand(bagel, BAGEL::rep_range)
#BAGEL::build_standard_table(bagel, g, "SNV192", "Transcript_Strand")
#BAGEL::build_standard_table(bagel, g, "SNV192", "Replication_Strand")
#
#####TEST WITH PANLUNG/MELANOMA
#standard <- BAGEL::discover_signatures(bagel, "SNV96", 4, "nmf")
#compare_cosmic_v2(standard, threshold = 0.9, result_name = "BRCA")
#
#trans_192 <- BAGEL::discover_signatures(bagel, "SNV192_Trans", 4, "nmf")
#plot_signatures(trans_192, plotly = TRUE)
#
#rep_192 <- BAGEL::discover_signatures(bagel, "SNV192_Rep", 4, "nmf")
#plot_signatures(rep_192, plotly = TRUE)
```
